version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    restart: always
    ports:
      - 8001:5000
    volumes:
      - .:/app
    environment:
      - FLASK_APP=main.py
    depends_on:
      - db
      - queue

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: main_ms_flask_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 5433:5432
    volumes:
      - .dbdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - 8082:80
    depends_on:
      - db
